# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ce12d252711b470af52b70f574388080adb59c0b10a144c228352a5b4725937d004a15284e6eadbc36de147533b92eac510be14bae259a06947a158009ab96b

test:
  secret_key_base: 2ffe07ed948ac6c8c6a0f6deb08e6b07f22951a6a1f72fe4bd99c5fcb1ba8ff03f19e11677f0e48103d8b2b8cf5c41d498b8334e16cd422a50a3e6378628f7df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
